export const options = [
	"Drunk Family Member",
	"Gross Green Beans",
	"Deviled Eggs",
	"Weird Story Told",
	"Politics Bad",
	"Cheesy Cornbread",
	"Bad Joke",
	"Something Too Spicy",
	"Someone Cries",
	"Couple Arguement",
	"Kid Cries",
	"Convo With Stranger",
	"Rizzler",
	"A TYSLY quote",
	"Spilt Drink",
	"Glizzy Talk",
	"Uncomfortable Talking to Strangers",
	"Chiefsgiving",
	"Football Talk",
	"Thank the Chef",
	"Bobs Burgers Reference",
	"Gotta Pee",
	"Meme Shared",
	"Food Good",
	"Food on Shirt (Stained)",
	"Smoke Break",
	"Steven Name Debate",
	"I Wish I Could Have Wine",
	"Todd is Black", 
	"Pants to the Ground",
	"Say something in Español",
	"$5 football",
	"Make Someone Finish Thier Drink",
	"Give A Hug"
];
