export const options = [
	"Drunk Family Member",
	"Gross Green Beans",
	"Deviled Eggs",
	"Weird Story Told",
	"Politics Bad",
	"Cheesy Cornbread",
	"Bad Joke",
	"Something Too Spicy",
	"Someone Crys",
	"Couple Arguement",
	"Kid Cries",
	"Convo With Stranger",
	"Rizzler",
	"A TYSLY quote",
	"Spilt Drink",
	"Glizzy Talk",
	"Uncomfortable Talking to Strangers",
	"Chiefsgiving",
	"Football Talk",
	"Thank the Chef",
	"Bobs Burgers Reference",
	"Gotta Pee",
	"Meme Shared",
	"Food Good",
	"Food on Shirt (Stained)",
	"Smoke Break",
];
